// Code generated by tool. DO NOT EDIT.
// app: goim, biz: auth

package errno

import (
	"github.com/crazyfrankie/goim/pkg/errorx/code"
)

const (
	ErrTokenInvalidCode              = 103101
	errTokenInvalidMessage           = "token is invalid"
	errTokenInvalidNoAffectStability = true
)

func init() {

	code.Register(
		ErrTokenInvalidCode,
		errTokenInvalidMessage,
		code.WithAffectStability(!errTokenInvalidNoAffectStability),
	)

}
