// Code generated by tool. DO NOT EDIT.
// app: goim, biz: common

package errno

import (
	"github.com/crazyfrankie/goim/pkg/errorx/code"
)

const (
	ErrNoPermissionCode              = 100101
	errNoPermissionMessage           = "no permission, ownerID: {owner_id}"
	errNoPermissionNoAffectStability = true
)

func init() {

	code.Register(
		ErrNoPermissionCode,
		errNoPermissionMessage,
		code.WithAffectStability(!errNoPermissionNoAffectStability),
	)

}
