// Code generated by tool. DO NOT EDIT.
// app: goim, biz: user

package errno

import (
	"github.com/crazyfrankie/goim/pkg/errorx/code"
)

const (
	ErrUserInvalidParamCode              = 101101
	errUserInvalidParamMessage           = "invalid parameter : {msg}"
	errUserInvalidParamNoAffectStability = true

	ErrUserInfoInvalidCode              = 101102
	errUserInfoInvalidMessage           = "invalid email or password, please try again."
	errUserInfoInvalidNoAffectStability = true

	ErrUserEmailAlreadyExistCode              = 101103
	errUserEmailAlreadyExistMessage           = "email already exist : {email}"
	errUserEmailAlreadyExistNoAffectStability = true

	ErrUserUniqueNameAlreadyExistCode              = 101104
	errUserUniqueNameAlreadyExistMessage           = "unique name already exist : {name}"
	errUserUniqueNameAlreadyExistNoAffectStability = true
)

func init() {

	code.Register(
		ErrUserInvalidParamCode,
		errUserInvalidParamMessage,
		code.WithAffectStability(!errUserInvalidParamNoAffectStability),
	)

	code.Register(
		ErrUserInfoInvalidCode,
		errUserInfoInvalidMessage,
		code.WithAffectStability(!errUserInfoInvalidNoAffectStability),
	)

	code.Register(
		ErrUserEmailAlreadyExistCode,
		errUserEmailAlreadyExistMessage,
		code.WithAffectStability(!errUserEmailAlreadyExistNoAffectStability),
	)

	code.Register(
		ErrUserUniqueNameAlreadyExistCode,
		errUserUniqueNameAlreadyExistMessage,
		code.WithAffectStability(!errUserUniqueNameAlreadyExistNoAffectStability),
	)

}
