// Code generated by tool. DO NOT EDIT.
// app: goim, biz: ws

package errno

import (
	"github.com/crazyfrankie/goim/pkg/errorx/code"
)

const (
	ErrConnArgsCode              = 102101
	errConnArgsMessage           = "args err, need token, sendID, platformID"
	errConnArgsNoAffectStability = true
)

func init() {

	code.Register(
		ErrConnArgsCode,
		errConnArgsMessage,
		code.WithAffectStability(!errConnArgsNoAffectStability),
	)

}
