// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: idl/msggateway/v1/msggateway.proto

package msggatewayv1

import (
	v1 "github.com/crazyfrankie/goim/protocol/msg/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlinePushMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *v1.Message            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PushToUserID  int64                  `protobuf:"varint,2,opt,name=pushToUserID,proto3" json:"pushToUserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePushMsgRequest) Reset() {
	*x = OnlinePushMsgRequest{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePushMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePushMsgRequest) ProtoMessage() {}

func (x *OnlinePushMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePushMsgRequest.ProtoReflect.Descriptor instead.
func (*OnlinePushMsgRequest) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{0}
}

func (x *OnlinePushMsgRequest) GetMessage() *v1.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *OnlinePushMsgRequest) GetPushToUserID() int64 {
	if x != nil {
		return x.PushToUserID
	}
	return 0
}

type OnlinePushMsgResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Resp          []*SingleMsgToUserPlatform `protobuf:"bytes,1,rep,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePushMsgResponse) Reset() {
	*x = OnlinePushMsgResponse{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePushMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePushMsgResponse) ProtoMessage() {}

func (x *OnlinePushMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePushMsgResponse.ProtoReflect.Descriptor instead.
func (*OnlinePushMsgResponse) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{1}
}

func (x *OnlinePushMsgResponse) GetResp() []*SingleMsgToUserPlatform {
	if x != nil {
		return x.Resp
	}
	return nil
}

type GetUsersOnlineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        []string               `protobuf:"bytes,1,rep,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusRequest) Reset() {
	*x = GetUsersOnlineStatusRequest{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusRequest) ProtoMessage() {}

func (x *GetUsersOnlineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusRequest) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersOnlineStatusRequest) GetUserID() []string {
	if x != nil {
		return x.UserID
	}
	return nil
}

type GetUsersOnlineStatusResponse struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	SuccessResult []*GetUsersOnlineStatusResponse_SuccessResult `protobuf:"bytes,1,rep,name=successResult,proto3" json:"successResult,omitempty"`
	FailedResult  []*GetUsersOnlineStatusResponse_FailedDetail  `protobuf:"bytes,2,rep,name=failedResult,proto3" json:"failedResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResponse) Reset() {
	*x = GetUsersOnlineStatusResponse{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResponse) ProtoMessage() {}

func (x *GetUsersOnlineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResponse) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersOnlineStatusResponse) GetSuccessResult() []*GetUsersOnlineStatusResponse_SuccessResult {
	if x != nil {
		return x.SuccessResult
	}
	return nil
}

func (x *GetUsersOnlineStatusResponse) GetFailedResult() []*GetUsersOnlineStatusResponse_FailedDetail {
	if x != nil {
		return x.FailedResult
	}
	return nil
}

type SingleMsgToUserPlatform struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResultCode     int64                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	RecvID         string                 `protobuf:"bytes,2,opt,name=recvID,proto3" json:"recvID,omitempty"`
	RecvPlatFormID int32                  `protobuf:"varint,3,opt,name=recvPlatFormID,proto3" json:"recvPlatFormID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SingleMsgToUserPlatform) Reset() {
	*x = SingleMsgToUserPlatform{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMsgToUserPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMsgToUserPlatform) ProtoMessage() {}

func (x *SingleMsgToUserPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMsgToUserPlatform.ProtoReflect.Descriptor instead.
func (*SingleMsgToUserPlatform) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{4}
}

func (x *SingleMsgToUserPlatform) GetResultCode() int64 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *SingleMsgToUserPlatform) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *SingleMsgToUserPlatform) GetRecvPlatFormID() int32 {
	if x != nil {
		return x.RecvPlatFormID
	}
	return 0
}

type SingleMsgToUserResults struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserID        string                     `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Resp          []*SingleMsgToUserPlatform `protobuf:"bytes,2,rep,name=resp,proto3" json:"resp,omitempty"`
	OnlinePush    bool                       `protobuf:"varint,3,opt,name=onlinePush,proto3" json:"onlinePush,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleMsgToUserResults) Reset() {
	*x = SingleMsgToUserResults{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMsgToUserResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMsgToUserResults) ProtoMessage() {}

func (x *SingleMsgToUserResults) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMsgToUserResults.ProtoReflect.Descriptor instead.
func (*SingleMsgToUserResults) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{5}
}

func (x *SingleMsgToUserResults) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SingleMsgToUserResults) GetResp() []*SingleMsgToUserPlatform {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *SingleMsgToUserResults) GetOnlinePush() bool {
	if x != nil {
		return x.OnlinePush
	}
	return false
}

type OnlineBatchPushOneMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *v1.Message            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PushToUserIDs []string               `protobuf:"bytes,2,rep,name=pushToUserIDs,proto3" json:"pushToUserIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineBatchPushOneMsgRequest) Reset() {
	*x = OnlineBatchPushOneMsgRequest{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineBatchPushOneMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBatchPushOneMsgRequest) ProtoMessage() {}

func (x *OnlineBatchPushOneMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBatchPushOneMsgRequest.ProtoReflect.Descriptor instead.
func (*OnlineBatchPushOneMsgRequest) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{6}
}

func (x *OnlineBatchPushOneMsgRequest) GetMessage() *v1.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *OnlineBatchPushOneMsgRequest) GetPushToUserIDs() []string {
	if x != nil {
		return x.PushToUserIDs
	}
	return nil
}

type OnlineBatchPushOneMsgResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SinglePushResult []*SingleMsgToUserResults `protobuf:"bytes,1,rep,name=singlePushResult,proto3" json:"singlePushResult,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OnlineBatchPushOneMsgResponse) Reset() {
	*x = OnlineBatchPushOneMsgResponse{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineBatchPushOneMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBatchPushOneMsgResponse) ProtoMessage() {}

func (x *OnlineBatchPushOneMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBatchPushOneMsgResponse.ProtoReflect.Descriptor instead.
func (*OnlineBatchPushOneMsgResponse) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{7}
}

func (x *OnlineBatchPushOneMsgResponse) GetSinglePushResult() []*SingleMsgToUserResults {
	if x != nil {
		return x.SinglePushResult
	}
	return nil
}

type KickUserOfflineRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformID     int32                  `protobuf:"varint,1,opt,name=platformID,proto3" json:"platformID,omitempty"`
	KickUserIDList []string               `protobuf:"bytes,2,rep,name=kickUserIDList,proto3" json:"kickUserIDList,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KickUserOfflineRequest) Reset() {
	*x = KickUserOfflineRequest{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserOfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserOfflineRequest) ProtoMessage() {}

func (x *KickUserOfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserOfflineRequest.ProtoReflect.Descriptor instead.
func (*KickUserOfflineRequest) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{8}
}

func (x *KickUserOfflineRequest) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *KickUserOfflineRequest) GetKickUserIDList() []string {
	if x != nil {
		return x.KickUserIDList
	}
	return nil
}

type KickUserOfflineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserOfflineResponse) Reset() {
	*x = KickUserOfflineResponse{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserOfflineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserOfflineResponse) ProtoMessage() {}

func (x *KickUserOfflineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserOfflineResponse.ProtoReflect.Descriptor instead.
func (*KickUserOfflineResponse) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{9}
}

type MultiTerminalLoginCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	PlatformID    int32                  `protobuf:"varint,2,opt,name=platformID,proto3" json:"platformID,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTerminalLoginCheckRequest) Reset() {
	*x = MultiTerminalLoginCheckRequest{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTerminalLoginCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTerminalLoginCheckRequest) ProtoMessage() {}

func (x *MultiTerminalLoginCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTerminalLoginCheckRequest.ProtoReflect.Descriptor instead.
func (*MultiTerminalLoginCheckRequest) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{10}
}

func (x *MultiTerminalLoginCheckRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MultiTerminalLoginCheckRequest) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *MultiTerminalLoginCheckRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MultiTerminalLoginCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTerminalLoginCheckResponse) Reset() {
	*x = MultiTerminalLoginCheckResponse{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTerminalLoginCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTerminalLoginCheckResponse) ProtoMessage() {}

func (x *MultiTerminalLoginCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTerminalLoginCheckResponse.ProtoReflect.Descriptor instead.
func (*MultiTerminalLoginCheckResponse) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{11}
}

type GetUsersOnlineStatusResponse_SuccessDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformID    int32                  `protobuf:"varint,1,opt,name=platformID,proto3" json:"platformID,omitempty"`
	ConnID        string                 `protobuf:"bytes,2,opt,name=connID,proto3" json:"connID,omitempty"`
	IsBackground  bool                   `protobuf:"varint,3,opt,name=isBackground,proto3" json:"isBackground,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResponse_SuccessDetail) Reset() {
	*x = GetUsersOnlineStatusResponse_SuccessDetail{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResponse_SuccessDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResponse_SuccessDetail) ProtoMessage() {}

func (x *GetUsersOnlineStatusResponse_SuccessDetail) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResponse_SuccessDetail.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResponse_SuccessDetail) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetUsersOnlineStatusResponse_SuccessDetail) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *GetUsersOnlineStatusResponse_SuccessDetail) GetConnID() string {
	if x != nil {
		return x.ConnID
	}
	return ""
}

func (x *GetUsersOnlineStatusResponse_SuccessDetail) GetIsBackground() bool {
	if x != nil {
		return x.IsBackground
	}
	return false
}

func (x *GetUsersOnlineStatusResponse_SuccessDetail) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUsersOnlineStatusResponse_FailedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResponse_FailedDetail) Reset() {
	*x = GetUsersOnlineStatusResponse_FailedDetail{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResponse_FailedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResponse_FailedDetail) ProtoMessage() {}

func (x *GetUsersOnlineStatusResponse_FailedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResponse_FailedDetail.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResponse_FailedDetail) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetUsersOnlineStatusResponse_FailedDetail) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetUsersOnlineStatusResponse_SuccessResult struct {
	state                protoimpl.MessageState                        `protogen:"open.v1"`
	UserID               string                                        `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Status               int32                                         `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	DetailPlatformStatus []*GetUsersOnlineStatusResponse_SuccessDetail `protobuf:"bytes,3,rep,name=detailPlatformStatus,proto3" json:"detailPlatformStatus,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResponse_SuccessResult) Reset() {
	*x = GetUsersOnlineStatusResponse_SuccessResult{}
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResponse_SuccessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResponse_SuccessResult) ProtoMessage() {}

func (x *GetUsersOnlineStatusResponse_SuccessResult) ProtoReflect() protoreflect.Message {
	mi := &file_idl_msggateway_v1_msggateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResponse_SuccessResult.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResponse_SuccessResult) Descriptor() ([]byte, []int) {
	return file_idl_msggateway_v1_msggateway_proto_rawDescGZIP(), []int{3, 2}
}

func (x *GetUsersOnlineStatusResponse_SuccessResult) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetUsersOnlineStatusResponse_SuccessResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUsersOnlineStatusResponse_SuccessResult) GetDetailPlatformStatus() []*GetUsersOnlineStatusResponse_SuccessDetail {
	if x != nil {
		return x.DetailPlatformStatus
	}
	return nil
}

var File_idl_msggateway_v1_msggateway_proto protoreflect.FileDescriptor

const file_idl_msggateway_v1_msggateway_proto_rawDesc = "" +
	"\n" +
	"\"idl/msggateway/v1/msggateway.proto\x12\rmsggateway.v1\x1a\x18idl/msg/v1/message.proto\"e\n" +
	"\x14OnlinePushMsgRequest\x12)\n" +
	"\amessage\x18\x01 \x01(\v2\x0f.msg.v1.MessageR\amessage\x12\"\n" +
	"\fpushToUserID\x18\x02 \x01(\x03R\fpushToUserID\"S\n" +
	"\x15OnlinePushMsgResponse\x12:\n" +
	"\x04resp\x18\x01 \x03(\v2&.msggateway.v1.SingleMsgToUserPlatformR\x04resp\"5\n" +
	"\x1bGetUsersOnlineStatusRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x03(\tR\x06userID\"\xba\x04\n" +
	"\x1cGetUsersOnlineStatusResponse\x12_\n" +
	"\rsuccessResult\x18\x01 \x03(\v29.msggateway.v1.GetUsersOnlineStatusResponse.SuccessResultR\rsuccessResult\x12\\\n" +
	"\ffailedResult\x18\x02 \x03(\v28.msggateway.v1.GetUsersOnlineStatusResponse.FailedDetailR\ffailedResult\x1a\x81\x01\n" +
	"\rSuccessDetail\x12\x1e\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x05R\n" +
	"platformID\x12\x16\n" +
	"\x06connID\x18\x02 \x01(\tR\x06connID\x12\"\n" +
	"\fisBackground\x18\x03 \x01(\bR\fisBackground\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x1a&\n" +
	"\fFailedDetail\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x1a\xae\x01\n" +
	"\rSuccessResult\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12m\n" +
	"\x14detailPlatformStatus\x18\x03 \x03(\v29.msggateway.v1.GetUsersOnlineStatusResponse.SuccessDetailR\x14detailPlatformStatus\"y\n" +
	"\x17SingleMsgToUserPlatform\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x03R\n" +
	"resultCode\x12\x16\n" +
	"\x06recvID\x18\x02 \x01(\tR\x06recvID\x12&\n" +
	"\x0erecvPlatFormID\x18\x03 \x01(\x05R\x0erecvPlatFormID\"\x8c\x01\n" +
	"\x16SingleMsgToUserResults\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12:\n" +
	"\x04resp\x18\x02 \x03(\v2&.msggateway.v1.SingleMsgToUserPlatformR\x04resp\x12\x1e\n" +
	"\n" +
	"onlinePush\x18\x03 \x01(\bR\n" +
	"onlinePush\"o\n" +
	"\x1cOnlineBatchPushOneMsgRequest\x12)\n" +
	"\amessage\x18\x01 \x01(\v2\x0f.msg.v1.MessageR\amessage\x12$\n" +
	"\rpushToUserIDs\x18\x02 \x03(\tR\rpushToUserIDs\"r\n" +
	"\x1dOnlineBatchPushOneMsgResponse\x12Q\n" +
	"\x10singlePushResult\x18\x01 \x03(\v2%.msggateway.v1.SingleMsgToUserResultsR\x10singlePushResult\"`\n" +
	"\x16KickUserOfflineRequest\x12\x1e\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x05R\n" +
	"platformID\x12&\n" +
	"\x0ekickUserIDList\x18\x02 \x03(\tR\x0ekickUserIDList\"\x19\n" +
	"\x17KickUserOfflineResponse\"n\n" +
	"\x1eMultiTerminalLoginCheckRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"platformID\x18\x02 \x01(\x05R\n" +
	"platformID\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"!\n" +
	"\x1fMultiTerminalLoginCheckResponse2\xa7\x05\n" +
	"\n" +
	"msgGateway\x12Z\n" +
	"\rOnlinePushMsg\x12#.msggateway.v1.OnlinePushMsgRequest\x1a$.msggateway.v1.OnlinePushMsgResponse\x12o\n" +
	"\x14GetUsersOnlineStatus\x12*.msggateway.v1.GetUsersOnlineStatusRequest\x1a+.msggateway.v1.GetUsersOnlineStatusResponse\x12r\n" +
	"\x15OnlineBatchPushOneMsg\x12+.msggateway.v1.OnlineBatchPushOneMsgRequest\x1a,.msggateway.v1.OnlineBatchPushOneMsgResponse\x12|\n" +
	"\x1fSuperGroupOnlineBatchPushOneMsg\x12+.msggateway.v1.OnlineBatchPushOneMsgRequest\x1a,.msggateway.v1.OnlineBatchPushOneMsgResponse\x12`\n" +
	"\x0fKickUserOffline\x12%.msggateway.v1.KickUserOfflineRequest\x1a&.msggateway.v1.KickUserOfflineResponse\x12x\n" +
	"\x17MultiTerminalLoginCheck\x12-.msggateway.v1.MultiTerminalLoginCheckRequest\x1a..msggateway.v1.MultiTerminalLoginCheckResponseBBZ@github.com/crazyfrankie/goim/protocol/msggateway/v1;msggatewayv1b\x06proto3"

var (
	file_idl_msggateway_v1_msggateway_proto_rawDescOnce sync.Once
	file_idl_msggateway_v1_msggateway_proto_rawDescData []byte
)

func file_idl_msggateway_v1_msggateway_proto_rawDescGZIP() []byte {
	file_idl_msggateway_v1_msggateway_proto_rawDescOnce.Do(func() {
		file_idl_msggateway_v1_msggateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_msggateway_v1_msggateway_proto_rawDesc), len(file_idl_msggateway_v1_msggateway_proto_rawDesc)))
	})
	return file_idl_msggateway_v1_msggateway_proto_rawDescData
}

var file_idl_msggateway_v1_msggateway_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_idl_msggateway_v1_msggateway_proto_goTypes = []any{
	(*OnlinePushMsgRequest)(nil),                       // 0: msggateway.v1.OnlinePushMsgRequest
	(*OnlinePushMsgResponse)(nil),                      // 1: msggateway.v1.OnlinePushMsgResponse
	(*GetUsersOnlineStatusRequest)(nil),                // 2: msggateway.v1.GetUsersOnlineStatusRequest
	(*GetUsersOnlineStatusResponse)(nil),               // 3: msggateway.v1.GetUsersOnlineStatusResponse
	(*SingleMsgToUserPlatform)(nil),                    // 4: msggateway.v1.SingleMsgToUserPlatform
	(*SingleMsgToUserResults)(nil),                     // 5: msggateway.v1.SingleMsgToUserResults
	(*OnlineBatchPushOneMsgRequest)(nil),               // 6: msggateway.v1.OnlineBatchPushOneMsgRequest
	(*OnlineBatchPushOneMsgResponse)(nil),              // 7: msggateway.v1.OnlineBatchPushOneMsgResponse
	(*KickUserOfflineRequest)(nil),                     // 8: msggateway.v1.KickUserOfflineRequest
	(*KickUserOfflineResponse)(nil),                    // 9: msggateway.v1.KickUserOfflineResponse
	(*MultiTerminalLoginCheckRequest)(nil),             // 10: msggateway.v1.MultiTerminalLoginCheckRequest
	(*MultiTerminalLoginCheckResponse)(nil),            // 11: msggateway.v1.MultiTerminalLoginCheckResponse
	(*GetUsersOnlineStatusResponse_SuccessDetail)(nil), // 12: msggateway.v1.GetUsersOnlineStatusResponse.SuccessDetail
	(*GetUsersOnlineStatusResponse_FailedDetail)(nil),  // 13: msggateway.v1.GetUsersOnlineStatusResponse.FailedDetail
	(*GetUsersOnlineStatusResponse_SuccessResult)(nil), // 14: msggateway.v1.GetUsersOnlineStatusResponse.SuccessResult
	(*v1.Message)(nil),                                 // 15: msg.v1.Message
}
var file_idl_msggateway_v1_msggateway_proto_depIdxs = []int32{
	15, // 0: msggateway.v1.OnlinePushMsgRequest.message:type_name -> msg.v1.Message
	4,  // 1: msggateway.v1.OnlinePushMsgResponse.resp:type_name -> msggateway.v1.SingleMsgToUserPlatform
	14, // 2: msggateway.v1.GetUsersOnlineStatusResponse.successResult:type_name -> msggateway.v1.GetUsersOnlineStatusResponse.SuccessResult
	13, // 3: msggateway.v1.GetUsersOnlineStatusResponse.failedResult:type_name -> msggateway.v1.GetUsersOnlineStatusResponse.FailedDetail
	4,  // 4: msggateway.v1.SingleMsgToUserResults.resp:type_name -> msggateway.v1.SingleMsgToUserPlatform
	15, // 5: msggateway.v1.OnlineBatchPushOneMsgRequest.message:type_name -> msg.v1.Message
	5,  // 6: msggateway.v1.OnlineBatchPushOneMsgResponse.singlePushResult:type_name -> msggateway.v1.SingleMsgToUserResults
	12, // 7: msggateway.v1.GetUsersOnlineStatusResponse.SuccessResult.detailPlatformStatus:type_name -> msggateway.v1.GetUsersOnlineStatusResponse.SuccessDetail
	0,  // 8: msggateway.v1.msgGateway.OnlinePushMsg:input_type -> msggateway.v1.OnlinePushMsgRequest
	2,  // 9: msggateway.v1.msgGateway.GetUsersOnlineStatus:input_type -> msggateway.v1.GetUsersOnlineStatusRequest
	6,  // 10: msggateway.v1.msgGateway.OnlineBatchPushOneMsg:input_type -> msggateway.v1.OnlineBatchPushOneMsgRequest
	6,  // 11: msggateway.v1.msgGateway.SuperGroupOnlineBatchPushOneMsg:input_type -> msggateway.v1.OnlineBatchPushOneMsgRequest
	8,  // 12: msggateway.v1.msgGateway.KickUserOffline:input_type -> msggateway.v1.KickUserOfflineRequest
	10, // 13: msggateway.v1.msgGateway.MultiTerminalLoginCheck:input_type -> msggateway.v1.MultiTerminalLoginCheckRequest
	1,  // 14: msggateway.v1.msgGateway.OnlinePushMsg:output_type -> msggateway.v1.OnlinePushMsgResponse
	3,  // 15: msggateway.v1.msgGateway.GetUsersOnlineStatus:output_type -> msggateway.v1.GetUsersOnlineStatusResponse
	7,  // 16: msggateway.v1.msgGateway.OnlineBatchPushOneMsg:output_type -> msggateway.v1.OnlineBatchPushOneMsgResponse
	7,  // 17: msggateway.v1.msgGateway.SuperGroupOnlineBatchPushOneMsg:output_type -> msggateway.v1.OnlineBatchPushOneMsgResponse
	9,  // 18: msggateway.v1.msgGateway.KickUserOffline:output_type -> msggateway.v1.KickUserOfflineResponse
	11, // 19: msggateway.v1.msgGateway.MultiTerminalLoginCheck:output_type -> msggateway.v1.MultiTerminalLoginCheckResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_idl_msggateway_v1_msggateway_proto_init() }
func file_idl_msggateway_v1_msggateway_proto_init() {
	if File_idl_msggateway_v1_msggateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_msggateway_v1_msggateway_proto_rawDesc), len(file_idl_msggateway_v1_msggateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_msggateway_v1_msggateway_proto_goTypes,
		DependencyIndexes: file_idl_msggateway_v1_msggateway_proto_depIdxs,
		MessageInfos:      file_idl_msggateway_v1_msggateway_proto_msgTypes,
	}.Build()
	File_idl_msggateway_v1_msggateway_proto = out.File
	file_idl_msggateway_v1_msggateway_proto_goTypes = nil
	file_idl_msggateway_v1_msggateway_proto_depIdxs = nil
}
