// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "message"

// Message Message Table
type Message struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:Message ID" json:"id"`                  // Message ID
	SendID      int64  `gorm:"column:send_id;not null;comment:Sender ID" json:"send_id"`                              // Sender ID
	RecvID      int64  `gorm:"column:recv_id;not null;comment:Receiver ID" json:"recv_id"`                            // Receiver ID
	GroupID     int64  `gorm:"column:group_id;not null;comment:Group ID" json:"group_id"`                             // Group ID
	ClientMsgID int64  `gorm:"column:client_msg_id;not null;comment:Client Message ID" json:"client_msg_id"`          // Client Message ID
	SessionType int32  `gorm:"column:session_type;not null;comment:Session Type" json:"session_type"`                 // Session Type
	MessageFrom int32  `gorm:"column:message_from;not null;comment:Message Source" json:"message_from"`               // Message Source
	ContentType int32  `gorm:"column:content_type;not null;comment:Message Content Type" json:"content_type"`         // Message Content Type
	Content     string `gorm:"column:content;not null;comment:Message Content" json:"content"`                        // Message Content
	Seq         int64  `gorm:"column:seq;not null;comment:Message Sequence Number" json:"seq"`                        // Message Sequence Number
	SendTime    int64  `gorm:"column:send_time;not null;comment:Send Time (Milliseconds)" json:"send_time"`           // Send Time (Milliseconds)
	Status      int32  `gorm:"column:status;not null;comment:Message Status" json:"status"`                           // Message Status
	IsRead      bool   `gorm:"column:is_read;not null;comment:Message Read Status" json:"is_read"`                    // Message Read Status
	CreatedTime int64  `gorm:"column:created_time;not null;comment:Creation Time (Milliseconds)" json:"created_time"` // Creation Time (Milliseconds)
	UpdatedTime int64  `gorm:"column:updated_time;not null;comment:Update Time (Milliseconds)" json:"updated_time"`   // Update Time (Milliseconds)
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
