// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: idl/push/v1/push.proto

package pushv1

import (
	v1 "github.com/crazyfrankie/goim/protocol/msg/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMsgRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        *v1.Message            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ConversationID string                 `protobuf:"bytes,2,opt,name=conversationID,proto3" json:"conversationID,omitempty"`
	UserIDs        []string               `protobuf:"bytes,3,rep,name=userIDs,proto3" json:"userIDs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushMsgRequest) Reset() {
	*x = PushMsgRequest{}
	mi := &file_idl_push_v1_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgRequest) ProtoMessage() {}

func (x *PushMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_push_v1_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgRequest.ProtoReflect.Descriptor instead.
func (*PushMsgRequest) Descriptor() ([]byte, []int) {
	return file_idl_push_v1_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsgRequest) GetMessage() *v1.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PushMsgRequest) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *PushMsgRequest) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type PushMsgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgResponse) Reset() {
	*x = PushMsgResponse{}
	mi := &file_idl_push_v1_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgResponse) ProtoMessage() {}

func (x *PushMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_push_v1_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgResponse.ProtoReflect.Descriptor instead.
func (*PushMsgResponse) Descriptor() ([]byte, []int) {
	return file_idl_push_v1_push_proto_rawDescGZIP(), []int{1}
}

type DelUserPushTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	PlatformID    int32                  `protobuf:"varint,2,opt,name=platformID,proto3" json:"platformID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserPushTokenRequest) Reset() {
	*x = DelUserPushTokenRequest{}
	mi := &file_idl_push_v1_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserPushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPushTokenRequest) ProtoMessage() {}

func (x *DelUserPushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_push_v1_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPushTokenRequest.ProtoReflect.Descriptor instead.
func (*DelUserPushTokenRequest) Descriptor() ([]byte, []int) {
	return file_idl_push_v1_push_proto_rawDescGZIP(), []int{2}
}

func (x *DelUserPushTokenRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DelUserPushTokenRequest) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

type DelUserPushTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserPushTokenResponse) Reset() {
	*x = DelUserPushTokenResponse{}
	mi := &file_idl_push_v1_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserPushTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPushTokenResponse) ProtoMessage() {}

func (x *DelUserPushTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_push_v1_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPushTokenResponse.ProtoReflect.Descriptor instead.
func (*DelUserPushTokenResponse) Descriptor() ([]byte, []int) {
	return file_idl_push_v1_push_proto_rawDescGZIP(), []int{3}
}

var File_idl_push_v1_push_proto protoreflect.FileDescriptor

const file_idl_push_v1_push_proto_rawDesc = "" +
	"\n" +
	"\x16idl/push/v1/push.proto\x12\apush.v1\x1a\x18idl/msg/v1/message.proto\"}\n" +
	"\x0ePushMsgRequest\x12)\n" +
	"\amessage\x18\x01 \x01(\v2\x0f.msg.v1.MessageR\amessage\x12&\n" +
	"\x0econversationID\x18\x02 \x01(\tR\x0econversationID\x12\x18\n" +
	"\auserIDs\x18\x03 \x03(\tR\auserIDs\"\x11\n" +
	"\x0fPushMsgResponse\"Q\n" +
	"\x17DelUserPushTokenRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"platformID\x18\x02 \x01(\x05R\n" +
	"platformID\"\x1a\n" +
	"\x18DelUserPushTokenResponse2f\n" +
	"\vPushService\x12W\n" +
	"\x10DelUserPushToken\x12 .push.v1.DelUserPushTokenRequest\x1a!.push.v1.DelUserPushTokenResponseB6Z4github.com/crazyfrankie/goim/protocol/push/v1;pushv1b\x06proto3"

var (
	file_idl_push_v1_push_proto_rawDescOnce sync.Once
	file_idl_push_v1_push_proto_rawDescData []byte
)

func file_idl_push_v1_push_proto_rawDescGZIP() []byte {
	file_idl_push_v1_push_proto_rawDescOnce.Do(func() {
		file_idl_push_v1_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_push_v1_push_proto_rawDesc), len(file_idl_push_v1_push_proto_rawDesc)))
	})
	return file_idl_push_v1_push_proto_rawDescData
}

var file_idl_push_v1_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_push_v1_push_proto_goTypes = []any{
	(*PushMsgRequest)(nil),           // 0: push.v1.PushMsgRequest
	(*PushMsgResponse)(nil),          // 1: push.v1.PushMsgResponse
	(*DelUserPushTokenRequest)(nil),  // 2: push.v1.DelUserPushTokenRequest
	(*DelUserPushTokenResponse)(nil), // 3: push.v1.DelUserPushTokenResponse
	(*v1.Message)(nil),               // 4: msg.v1.Message
}
var file_idl_push_v1_push_proto_depIdxs = []int32{
	4, // 0: push.v1.PushMsgRequest.message:type_name -> msg.v1.Message
	2, // 1: push.v1.PushService.DelUserPushToken:input_type -> push.v1.DelUserPushTokenRequest
	3, // 2: push.v1.PushService.DelUserPushToken:output_type -> push.v1.DelUserPushTokenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_push_v1_push_proto_init() }
func file_idl_push_v1_push_proto_init() {
	if File_idl_push_v1_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_push_v1_push_proto_rawDesc), len(file_idl_push_v1_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_push_v1_push_proto_goTypes,
		DependencyIndexes: file_idl_push_v1_push_proto_depIdxs,
		MessageInfos:      file_idl_push_v1_push_proto_msgTypes,
	}.Build()
	File_idl_push_v1_push_proto = out.File
	file_idl_push_v1_push_proto_goTypes = nil
	file_idl_push_v1_push_proto_depIdxs = nil
}
