// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: idl/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateConnTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConnTokenRequest) Reset() {
	*x = GenerateConnTokenRequest{}
	mi := &file_idl_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConnTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConnTokenRequest) ProtoMessage() {}

func (x *GenerateConnTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConnTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateConnTokenRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type GenerateConnTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConnTokenResponse) Reset() {
	*x = GenerateConnTokenResponse{}
	mi := &file_idl_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConnTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConnTokenResponse) ProtoMessage() {}

func (x *GenerateConnTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConnTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateConnTokenResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateConnTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ParseTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTokenRequest) Reset() {
	*x = ParseTokenRequest{}
	mi := &file_idl_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTokenRequest) ProtoMessage() {}

func (x *ParseTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTokenRequest.ProtoReflect.Descriptor instead.
func (*ParseTokenRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ParseTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ParseTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTokenResponse) Reset() {
	*x = ParseTokenResponse{}
	mi := &file_idl_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTokenResponse) ProtoMessage() {}

func (x *ParseTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTokenResponse.ProtoReflect.Descriptor instead.
func (*ParseTokenResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ParseTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RefreshBizTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshBizTokenRequest) Reset() {
	*x = RefreshBizTokenRequest{}
	mi := &file_idl_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshBizTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshBizTokenRequest) ProtoMessage() {}

func (x *RefreshBizTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshBizTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshBizTokenRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshBizTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshBizTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshBizTokenResponse) Reset() {
	*x = RefreshBizTokenResponse{}
	mi := &file_idl_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshBizTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshBizTokenResponse) ProtoMessage() {}

func (x *RefreshBizTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshBizTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshBizTokenResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshBizTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshBizTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshBizTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_idl_auth_v1_auth_proto protoreflect.FileDescriptor

const file_idl_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16idl/auth/v1/auth.proto\x12\aauth.v1\"\x1a\n" +
	"\x18GenerateConnTokenRequest\"1\n" +
	"\x19GenerateConnTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\")\n" +
	"\x11ParseTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"-\n" +
	"\x12ParseTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"=\n" +
	"\x16RefreshBizTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"z\n" +
	"\x17RefreshBizTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId2\x86\x02\n" +
	"\vAuthService\x12Z\n" +
	"\x11GenerateConnToken\x12!.auth.v1.GenerateConnTokenRequest\x1a\".auth.v1.GenerateConnTokenResponse\x12E\n" +
	"\n" +
	"ParseToken\x12\x1a.auth.v1.ParseTokenRequest\x1a\x1b.auth.v1.ParseTokenResponse\x12T\n" +
	"\x0fRefreshBizToken\x12\x1f.auth.v1.RefreshBizTokenRequest\x1a .auth.v1.RefreshBizTokenResponseB6Z4github.com/crazyfrankie/goim/protocol/auth/v1;authv1b\x06proto3"

var (
	file_idl_auth_v1_auth_proto_rawDescOnce sync.Once
	file_idl_auth_v1_auth_proto_rawDescData []byte
)

func file_idl_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_idl_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_idl_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_auth_v1_auth_proto_rawDesc), len(file_idl_auth_v1_auth_proto_rawDesc)))
	})
	return file_idl_auth_v1_auth_proto_rawDescData
}

var file_idl_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_idl_auth_v1_auth_proto_goTypes = []any{
	(*GenerateConnTokenRequest)(nil),  // 0: auth.v1.GenerateConnTokenRequest
	(*GenerateConnTokenResponse)(nil), // 1: auth.v1.GenerateConnTokenResponse
	(*ParseTokenRequest)(nil),         // 2: auth.v1.ParseTokenRequest
	(*ParseTokenResponse)(nil),        // 3: auth.v1.ParseTokenResponse
	(*RefreshBizTokenRequest)(nil),    // 4: auth.v1.RefreshBizTokenRequest
	(*RefreshBizTokenResponse)(nil),   // 5: auth.v1.RefreshBizTokenResponse
}
var file_idl_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.GenerateConnToken:input_type -> auth.v1.GenerateConnTokenRequest
	2, // 1: auth.v1.AuthService.ParseToken:input_type -> auth.v1.ParseTokenRequest
	4, // 2: auth.v1.AuthService.RefreshBizToken:input_type -> auth.v1.RefreshBizTokenRequest
	1, // 3: auth.v1.AuthService.GenerateConnToken:output_type -> auth.v1.GenerateConnTokenResponse
	3, // 4: auth.v1.AuthService.ParseToken:output_type -> auth.v1.ParseTokenResponse
	5, // 5: auth.v1.AuthService.RefreshBizToken:output_type -> auth.v1.RefreshBizTokenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_auth_v1_auth_proto_init() }
func file_idl_auth_v1_auth_proto_init() {
	if File_idl_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_auth_v1_auth_proto_rawDesc), len(file_idl_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_idl_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_idl_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_idl_auth_v1_auth_proto = out.File
	file_idl_auth_v1_auth_proto_goTypes = nil
	file_idl_auth_v1_auth_proto_depIdxs = nil
}
